"""WAF detection and bypass strategy engine."""

from __future__ import annotations

import random
import re
import time
from dataclasses import dataclass, field
from typing import Any

import requests

# WAF signature database


@dataclass
class WAFSignature:
    name: str
    headers: dict[str, re.Pattern] = field(default_factory=dict)
    cookies: list[str] = field(default_factory=list)
    body_patterns: list[re.Pattern] = field(default_factory=list)
    status_codes: list[int] = field(default_factory=list)


WAF_SIGNATURES: list[WAFSignature] = [
    WAFSignature(
        name="Cloudflare",
        headers={"server": re.compile(r"cloudflare", re.I),
                 "cf-ray": re.compile(r".*")},
        cookies=["__cfduid", "cf_clearance", "__cf_bm"],
        body_patterns=[re.compile(r"cloudflare", re.I),
                       re.compile(r"Attention Required")],
    ),
    WAFSignature(
        name="AWS WAF",
        headers={"x-amzn-requestid": re.compile(r".*"),
                 "x-amz-apigw-id": re.compile(r".*")},
        body_patterns=[re.compile(r"aws", re.I)],
        status_codes=[403],
    ),
    WAFSignature(
        name="Akamai",
        headers={"server": re.compile(r"AkamaiGHost", re.I),
                 "x-akamai-transformed": re.compile(r".*")},
        body_patterns=[re.compile(r"Reference #\d+\.\w+")],
    ),
    WAFSignature(
        name="ModSecurity",
        headers={"server": re.compile(r"mod_security|NOYB", re.I)},
        body_patterns=[re.compile(r"ModSecurity|Mod_Security", re.I),
                       re.compile(r"not acceptable", re.I)],
        status_codes=[403, 406],
    ),
    WAFSignature(
        name="Imperva/Incapsula",
        headers={"x-iinfo": re.compile(r".*"),
                 "x-cdn": re.compile(r"Incapsula", re.I)},
        cookies=["incap_ses_", "visid_incap_"],
        body_patterns=[re.compile(r"Incapsula|_Incapsula_Resource", re.I)],
    ),
    WAFSignature(
        name="F5 BIG-IP ASM",
        headers={"server": re.compile(r"BIG-IP|BigIP", re.I)},
        cookies=["TS", "BIGipServer", "F5_"],
        body_patterns=[re.compile(r"The requested URL was rejected", re.I)],
    ),
    WAFSignature(
        name="Sucuri",
        headers={"server": re.compile(r"Sucuri", re.I),
                 "x-sucuri-id": re.compile(r".*"),
                 "x-sucuri-cache": re.compile(r".*")},
        body_patterns=[re.compile(r"sucuri|cloudproxy", re.I),
                       re.compile(r"Access Denied.*Sucuri", re.I)],
    ),
    WAFSignature(
        name="Barracuda",
        headers={"server": re.compile(r"Barracuda", re.I)},
        cookies=["barra_counter_session"],
        body_patterns=[re.compile(r"Barracuda", re.I)],
    ),
    WAFSignature(
        name="Fortinet/FortiWeb",
        headers={"server": re.compile(r"FortiWeb", re.I)},
        cookies=["FORTIWAFSID"],
        body_patterns=[re.compile(r"FortiWeb|fgd_icon", re.I)],
    ),
    WAFSignature(
        name="Citrix NetScaler",
        headers={"via": re.compile(r"NS-CACHE", re.I)},
        cookies=["ns_af", "citrix_ns_id", "NSC_"],
        body_patterns=[re.compile(r"ns_af|NetScaler", re.I)],
    ),
    WAFSignature(
        name="DenyAll",
        headers={"server": re.compile(r"DenyAll", re.I)},
        cookies=["sessioncookie"],
    ),
    WAFSignature(
        name="Wallarm",
        headers={"server": re.compile(r"nginx-wallarm", re.I)},
    ),
    WAFSignature(
        name="Radware/AppWall",
        headers={"x-sl-compstate": re.compile(r".*")},
        body_patterns=[re.compile(r"Unauthorized Activity", re.I)],
    ),
    WAFSignature(
        name="Edgecast/Verizon",
        headers={"server": re.compile(r"ECD|ECS", re.I)},
    ),
    WAFSignature(
        name="StackPath",
        headers={"x-sp-waf": re.compile(r".*"),
                 "server": re.compile(r"StackPath", re.I)},
    ),
    WAFSignature(
        name="Wordfence",
        body_patterns=[
            re.compile(r"wordfence|wfFunc", re.I),
            re.compile(r"This response was generated by Wordfence", re.I),
        ],
    ),
    WAFSignature(
        name="NAXSI",
        headers={"server": re.compile(r"naxsi", re.I)},
        body_patterns=[re.compile(r"NAXSI", re.I)],
        status_codes=[403],
    ),
    WAFSignature(
        name="SonicWall",
        headers={"server": re.compile(r"SonicWALL", re.I)},
        body_patterns=[re.compile(r"This request is blocked by the SonicWall", re.I)],
    ),
    WAFSignature(
        name="Azure Front Door",
        headers={"x-azure-ref": re.compile(r".*")},
    ),
    WAFSignature(
        name="Google Cloud Armor",
        body_patterns=[
            re.compile(r"Your client has issued a malformed or illegal request", re.I),
        ],
        status_codes=[403],
    ),
]


# User-Agent pool for rotation

USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0",
    "Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1",
    "Mozilla/5.0 (Linux; Android 14; SM-S918B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36",
    "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)",
    "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
]


# WAF Detector


@dataclass
class WAFResult:
    detected: bool = False
    waf_name: str = "Unknown"
    confidence: float = 0.0
    details: dict[str, Any] = field(default_factory=dict)


class WAFDetector:
    """Detect WAF presence by sending a known-bad request and analysing response."""

    PROBE_PAYLOADS = [
        "/?test=<script>alert(1)</script>",
        "/?id=1' OR 1=1--",
        "/?file=../../../../etc/passwd",
        "/?cmd=;cat /etc/passwd",
    ]

    def __init__(self, session: requests.Session | None = None) -> None:
        self.session = session or requests.Session()
        self.session.headers.setdefault("User-Agent", random.choice(USER_AGENTS))

    def detect(self, base_url: str) -> WAFResult:
        """
        Send probe requests and match responses against WAF signatures.
        Returns best-match WAFResult.
        """
        # Step 1: Baseline — normal request to get clean headers
        try:
            baseline = self.session.get(base_url, timeout=10, allow_redirects=True)
        except requests.RequestException:
            return WAFResult()

        # Step 2: Check baseline headers for WAF markers
        best = self._match_response(baseline)
        if best.detected and best.confidence >= 0.8:
            return best

        # Step 3: Trigger WAF with malicious probes
        for probe in self.PROBE_PAYLOADS:
            try:
                resp = self.session.get(
                    base_url.rstrip("/") + probe,
                    timeout=10,
                    allow_redirects=False,
                )
                result = self._match_response(resp)
                if result.confidence > best.confidence:
                    best = result
                if best.confidence >= 0.8:
                    return best
            except requests.RequestException:
                continue
            time.sleep(0.3)

        return best

    def _match_response(self, resp: requests.Response) -> WAFResult:
        """Score a response against all WAF signatures."""
        best = WAFResult()

        for sig in WAF_SIGNATURES:
            score = 0.0
            total_checks = 0
            details: dict[str, Any] = {}

            # Header matching
            for header_name, pattern in sig.headers.items():
                total_checks += 1
                value = resp.headers.get(header_name, "")
                if value and pattern.search(value):
                    score += 1
                    details[f"header:{header_name}"] = value

            # Cookie matching
            for cookie_prefix in sig.cookies:
                total_checks += 1
                for cookie_name in resp.cookies.keys():
                    if cookie_name.startswith(cookie_prefix) or cookie_name == cookie_prefix:
                        score += 1
                        details[f"cookie:{cookie_prefix}"] = True
                        break

            # Body pattern matching
            body_text = resp.text[:10000]  # Limit body scan
            for pattern in sig.body_patterns:
                total_checks += 1
                if pattern.search(body_text):
                    score += 1
                    details["body_match"] = pattern.pattern

            # Status code matching
            if sig.status_codes:
                total_checks += 1
                if resp.status_code in sig.status_codes:
                    score += 0.5

            if total_checks > 0:
                confidence = score / total_checks
            else:
                confidence = 0.0

            if confidence > best.confidence:
                best = WAFResult(
                    detected=confidence > 0.3,
                    waf_name=sig.name,
                    confidence=round(confidence, 2),
                    details=details,
                )

        return best


# WAF Bypass — request transformation pipeline

class WAFBypass:
    """
    Transforms outgoing requests to evade WAF detection.

    Strategies applied based on detected WAF:
      - User-Agent rotation
      - Header randomization
      - Request splitting / chunked encoding
      - Payload encoding (double-URL, Unicode, hex, case mutation)
      - Adding junk parameters to dilute signatures
    """

    def __init__(self, waf_result: WAFResult | None = None) -> None:
        self.waf = waf_result or WAFResult()
        self._ua_pool = list(USER_AGENTS)
        random.shuffle(self._ua_pool)
        self._ua_index = 0

    def get_headers(self) -> dict[str, str]:
        """Return randomised headers to evade WAF fingerprinting."""
        ua = self._ua_pool[self._ua_index % len(self._ua_pool)]
        self._ua_index += 1

        headers: dict[str, str] = {
            "User-Agent": ua,
            "Accept": random.choice([
                "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
                "*/*",
                "application/json, text/plain, */*",
            ]),
            "Accept-Language": random.choice([
                "en-US,en;q=0.9",
                "en-GB,en;q=0.5",
                "de-DE,de;q=0.9,en;q=0.5",
                "fr-FR,fr;q=0.9",
            ]),
            "Accept-Encoding": "gzip, deflate, br",
        }

        # Add junk headers to increase request entropy
        junk_headers = {
            "X-Forwarded-For": f"{random.randint(1,254)}.{random.randint(0,254)}.{random.randint(0,254)}.{random.randint(1,254)}",
            "X-Real-IP": f"10.{random.randint(0,255)}.{random.randint(0,255)}.{random.randint(1,254)}",
            "X-Originating-IP": f"192.168.{random.randint(0,255)}.{random.randint(1,254)}",
            "X-Client-IP": f"172.{random.randint(16,31)}.{random.randint(0,255)}.{random.randint(1,254)}",
        }

        # Only add some junk headers randomly
        for k, v in junk_headers.items():
            if random.random() > 0.5:
                headers[k] = v

        return headers

    def add_junk_params(self, url: str, count: int = 2) -> str:
        """Add random harmless query parameters to dilute WAF pattern matching."""
        separator = "&" if "?" in url else "?"
        params = []
        for _ in range(count):
            key = "".join(random.choices("abcdefghijklmnopqrstuvwxyz", k=random.randint(3, 8)))
            val = "".join(random.choices("0123456789abcdef", k=random.randint(4, 12)))
            params.append(f"{key}={val}")
        return url + separator + "&".join(params)

    def transform_request(
        self,
        session: requests.Session,
        method: str,
        url: str,
        **kwargs: Any,
    ) -> requests.Response:
        """
        Send request with WAF bypass transformations applied.
        """
        # Merge bypass headers
        existing_headers = kwargs.pop("headers", {}) or {}
        bypass_headers = self.get_headers()
        bypass_headers.update(existing_headers)
        kwargs["headers"] = bypass_headers

        # Add junk params
        if self.waf.detected and self.waf.confidence > 0.5:
            url = self.add_junk_params(url)

        # Small random delay to avoid rate-limit patterns
        if self.waf.detected:
            time.sleep(random.uniform(0.05, 0.3))

        return session.request(method, url, **kwargs)


def detect_and_prepare(
    base_url: str,
    session: requests.Session | None = None,
) -> tuple[WAFResult, WAFBypass]:
    """
    Convenience function: detect WAF and return a matching bypass engine.

    Usage:
        waf_result, bypass = detect_and_prepare("https://target.com")
        if waf_result.detected:
            console.print(f"WAF detected: {waf_result.waf_name}")
    """
    detector = WAFDetector(session)
    result = detector.detect(base_url)
    return result, WAFBypass(result)
